-- CRIAÇÃO E USO DO BANCO DE DADOS
CREATE DATABASE DB_ONBOARDING;
USE DB_ONBOARDING;

-- TABELAS
CREATE TABLE TB_USUARIOS (
	ID_USUARIO INT NOT NULL,
    NM_USUARIO VARCHAR(100),
    NM_EMAIL VARCHAR(100),
    NM_SENHA VARCHAR(100)
);

CREATE TABLE TB_ETAPAS (
	ID_ETAPA INT NOT NULL,
    NM_ETAPA VARCHAR(100),
    DS_DESCRICAO VARCHAR(280),
    DS_DURACAO VARCHAR(45),
    ID_USUARIO INT
);

CREATE TABLE TB_QUESTOES (
	ID_QUESTAO INT NOT NULL,
    DS_ETAPA VARCHAR(280),
    DS_ALTERNATIVAA VARCHAR(45),
    DS_ALTERNATIVAB VARCHAR(45),
    DS_ALTERNATIVAC VARCHAR(45),
    DS_ALTERNATIVAD VARCHAR(45),
    ID_ETAPA INT
);

CREATE TABLE TB_CERTAS (
	ID_CERTA INT,
    ID_QUESTAO INT
);

-- CHAVES PRIMARIAS
ALTER TABLE TB_USUARIOS ADD PRIMARY KEY (ID_USUARIO);
ALTER TABLE TB_ETAPAS ADD PRIMARY KEY (ID_ETAPA);
ALTER TABLE TB_QUESTOES ADD PRIMARY KEY (ID_QUESTAO);
ALTER TABLE TB_CERTAS ADD PRIMARY KEY (ID_CERTA);

-- CHAVES ESTRANGEIRAS
ALTER TABLE TB_ETAPAS ADD CONSTRAINT FK_USUARIO_ETAPA FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS (ID_USUARIO);
ALTER TABLE TB_QUESTOES ADD CONSTRAINT FK_ETAPA_QUESTOES FOREIGN KEY (ID_ETAPA) REFERENCES TB_ETAPAS (ID_ETAPA);
ALTER TABLE TB_CERTAS ADD CONSTRAINT FK_QUESTOES_CERTA FOREIGN KEY (ID_QUESTAO) REFERENCES TB_QUESTOES (ID_QUESTAO);